#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

: "${SPARK2_LATEST:=2.4.8}"

# Determine Rumble version
RUMBLE_VERSION="$(echo "$DOCKER_TAG" | cut -f1 -d-)"
RUMBLE_VERSION="${RUMBLE_VERSION:1}"

echo "Rumble version: $RUMBLE_VERSION"

# Determine exact Spark version and Rumble file name
spark_major="$(echo "$DOCKER_TAG" | sed "s/.*-spark//")"

if [[ "$spark_major" == "2" ]]
then
    # Rumble file name has changed with version 1.16.1
    if [[ "${RUMBLE_VERSION:0:2}" == "1." && "$(echo ${RUMBLE_VERSION:2:2} | tr -d .)" -le 16 && "${RUMBLE_VERSION}" != "1.16.1" ]]
    then
        suffix="-for-spark2"
    else
        suffix="-for-spark-2.4"
    fi

    SPARK_VERSION=$SPARK2_LATEST
    RUMBLE_FILENAME="v${RUMBLE_VERSION}/rumbledb-${RUMBLE_VERSION}${suffix}.jar"
elif [[ "$spark_major" == "3" ]]
then
    # Minor version of Spark 3 depends on Rumble version; Rumble file name has
    # changed with versions 1.14.0 and 1.16.1
    declare -A SPARK3_VERSIONS
    declare -A RUMBLE_FILENAMES
    v="1.11.0"; SPARK3_VERSIONS[$v]="3.0.3"; RUMBLE_FILENAMES[$v]=v$v/spark-rumble-$v.jar
    v="1.12.0"; SPARK3_VERSIONS[$v]="3.0.3"; RUMBLE_FILENAMES[$v]=v$v/spark-rumble-$v.jar
    v="1.14.0"; SPARK3_VERSIONS[$v]="3.0.3"; RUMBLE_FILENAMES[$v]=v$v/rumbledb-$v.jar
    v="1.15.0"; SPARK3_VERSIONS[$v]="3.1.2"; RUMBLE_FILENAMES[$v]=v$v/rumbledb-$v.jar
    v="1.16.0"; SPARK3_VERSIONS[$v]="3.1.2"; RUMBLE_FILENAMES[$v]=v$v/rumbledb-$v.jar
    v="1.16.1"; SPARK3_VERSIONS[$v]="3.1.2"; RUMBLE_FILENAMES[$v]=v$v/rumbledb-$v-for-spark-3.1.jar
    v="1.16.2"; SPARK3_VERSIONS[$v]="3.2.1"; RUMBLE_FILENAMES[$v]=v$v/rumbledb-$v-for-spark-3.2.jar
    v="1.17.0"; SPARK3_VERSIONS[$v]="3.2.1"; RUMBLE_FILENAMES[$v]=v$v/rumbledb-$v-for-spark-3.2.jar
    v="1.18.0"; SPARK3_VERSIONS[$v]="3.2.3"; RUMBLE_FILENAMES[$v]=v$v/rumbledb-$v-for-spark-3.2.jar
    v="1.19.0"; SPARK3_VERSIONS[$v]="3.2.3"; RUMBLE_FILENAMES[$v]=v$v/rumbledb-$v-for-spark-3.3.jar
    v="1.20.0"; SPARK3_VERSIONS[$v]="3.2.3"; RUMBLE_FILENAMES[$v]=v$v/rumbledb-$v-for-spark-3.3.jar

    SPARK_VERSION=${SPARK3_VERSIONS[$RUMBLE_VERSION]}
    RUMBLE_FILENAME=${RUMBLE_FILENAMES[$RUMBLE_VERSION]}
else
    echo "Error: could not detect Spark version." >&2
fi

echo "Rumble file name: $RUMBLE_FILENAME"
echo "Spark version: $SPARK_VERSION"

# Run build command
docker build "$ROOT_DIR" -t ${IMAGE_NAME} \
    --build-arg SPARK_VERSION=${SPARK_VERSION} \
    --build-arg RUMBLE_FILENAME=${RUMBLE_FILENAME}
